# Generated by Django 5.2.1 on 2025-05-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='super_admin_photo',
            field=models.ImageField(blank=True, null=True, upload_to='super_admin_pics'),
        ),
    ]
